apiVersion: codewind.dev/v1alpha1
kind: IterativeDevelopmentPack
metadata:
  name: java-liberty-pack
  language: java
  framework: liberty
spec:
  buildTasks:
    - name: maven-build
      buildImage: docker.io/maven:3.6
      command: mvn package
    - name: incremental-maven-build
      buildImage: docker.io/maven:3.6
      command: mvn compile
    - name: server-start
      command: /opt/ibm/wlp/bin/server start $SERVER
  runTasks:
    - name: server-start
      image: docker.io/ibmcom/websphere-liberty:latest
      command: /opt/ibm/wlp/bin/server start $SERVER
  scenarios:
    - name: full-build
      buildTasks: ["maven-build", "server-start"]
      runTasks: ["server-start"]
    - name: incremental-build
      buildTasks: ["incremental-maven-build", "server-start"]
      runTasks: ["server-start"]
